### ISSUE TITLE
Position isn't translated correctly from source to target when the armature rotations don't match

### ISSUE THREAD

**Issue by geneishouko** [nkeeline/Keemap-Blender-Rig-ReTargeting-Addon#8]
I have a need to retarget animations where the source and target armatures local spaces don't face the same direction. The target armature is rotated 90 degrees in the X axis to take into account the import tool of a certain game. The resulting animation for the target armature has the movement in the Y axis being applied to the Z axis and viceversa. To remedy this I applied a bone constraint on the Armature to copy the position of the source root bone after applying the entire retargeted animation. Is it possible for this addon to take into account Armature rotation?
![ksnip_20220225-154401](https://user-images.githubusercontent.com/38262047/155800313-6f5403d2-4ab0-4759-a417-7bc1a2805c77.png)
![ksnip_20220225-154427](https://user-images.githubusercontent.com/38262047/155800328-4a6fe8d4-84a9-416d-9fa9-8ec27b707b56.png)

**Comment by nkeeline** [comment]
Not sure I completely understand what you said,  but the script takes the global rotation of the source bone, then rotates the target bone to the same rotation with a correction rotation in global space.  This correction is calculated for you with the calc button when both rigs are in the 'same' position.  Armature Rotation is NEVER USED since all bone rotations are copied in WORLD SPACE.

**Comment by nkeeline** [comment]
I believe this is resolved with v0.0.5
